### ISSUE TITLE
Activity Form Not Rendering Properly

### ISSUE THREAD

**Issue by kevinlee12** [kevinlee12/iU#100]
### Description

Activity Form is not rendering properly when its on 623px. 

### Additional Info:
Browser: Chrome

### Screenshot: 
![image](https://cloud.githubusercontent.com/assets/5758256/8918943/638b3a5a-3470-11e5-8065-eb10e6b9adc5.png)

**Comment by kevinlee12** [comment]
@janicez11 , problem still persists.

**Comment by janicez11** [comment]
@kevinlee12 really? could u send me a screenshot cuz it works fine on my side.

**Comment by kevinlee12** [comment]
@janicez11 yes, at 640px. 
![image](https://cloud.githubusercontent.com/assets/5758256/9023715/676614c0-385c-11e5-8047-b5f937d663f5.png)

**Comment by janicez11** [comment]
are you sure ur looking at the new one?? works fine for me. 

![screen shot 2015-08-01 at 3 02 41 pm](https://cloud.githubusercontent.com/assets/11182000/9023754/66e2b768-385e-11e5-9503-8cf634be2c0a.png)

**Comment by kevinlee12** [comment]
I'm using the one on develop

**Comment by janicez11** [comment]
don't think this one is in develop yet.

**Comment by kevinlee12** [comment]
okay then, i'll wait until its on develop
