### ISSUE TITLE
Comment Area

### ISSUE THREAD

**Issue by kevinlee12** [kevinlee12/iU#102]
### Description

Alter the comment area so that its clear that its for comments to the user/coordinator/advisor. Also, do resize the text area so that its properly sized.

### Additional Info:

You might want to use vw or % when sizing, just make sure it looks consistent on mobile, half screen, and full screen on desktop. 

### Proposed (Screenshot): 
![image](https://cloud.githubusercontent.com/assets/5758256/8919450/43965d48-3474-11e5-92fd-64ebce16f268.png)

**Comment by janicez11** [comment]
I need some clarification for this one. Is this comment section for users to leave messages for the coordinators? or to see the message that the coordinator left for them ?

**Comment by kevinlee12** [comment]
The comment section is for both students and coordinators. Students can initiate or respond to comments with coordinators. (ie. Student: Coordinator can you look at this?)
