### ISSUE TITLE
Image Resizing Warning

### ISSUE THREAD

**Issue by kevinlee12** [kevinlee12/iU#104]
### Description

Warn the user that images that are larger than 1024 x 1024 pixels will be rejected. 

~~Warn the user whenever they choose to use the image reflection, that their image will be resized so that the longest side is 500px (preserving aspect ratio) if any of their longest side is over 500 px.~~

**Comment by janicez11** [comment]
I feel like this should come after all the text editor/image editor are finished

**Comment by kevinlee12** [comment]
:+1:

**Comment by kevinlee12** [comment]
as recommended, will kick this off until we complete summernote.

**Comment by kevinlee12** [comment]
@janicez11, you're free to tackle this now :smile:
